#
# ______ _            _    _   _                ___       _
# | ___ \ |          | |  | \ | |              |_  |     (_)
# | |_/ / | ___   ___| | _|  \| | _____      __  | | ___  _ _ __  ___
# | ___ \ |/ _ \ / __| |/ / . ` |/ _ \ \ /\ / /  | |/ _ \| | '_ \/ __|
# | |_/ / | (_) | (__|   <| |\  |  __/\ V  V /\__/ / (_) | | | | \__ \
# \____/|_|\___/ \___|_|\_\_| \_/\___| \_/\_/\____/ \___/|_|_| |_|___/
#
# Plugin made by Nookure Development for Minearte Network
# If you need help join our Discord: https://discord.nookure.com
#
# General configuration
Config:
  enable: true # Choose to enable or disable the new players kick.
  enableRedirectServer: true # Choose if new players will be redirected to another server. If false, players will be kicked.
  timeBeforeKick: 5 # Time in seconds before new players are disconnected/redirected.
  redirectServer: backend1 # Which server the new players will be redirected.
  disableMovement: true # Toggle if new players be able to move before they are disconnected/redirected.
  enableBlindness: true # Toggle if new players will have the blindness effect.
  enableTitle: true # Toggle if new players will receive a title.

# Plugin messages
Messages:
  prefix: '&6&lBNJ &8&l»'
  reload: '{prefix} &7BlockNewJoins has been reloaded.'
  warningNewPlayers:
    - ''
    - '&7████&c█&7████'
    - '&7███&c█&6█&c█&7███'
    - "&7██&c█&6█&0█&6█&c█&7██  &7This server doesn't allow new"
    - '&7██&c█&6█&0█&6█&c█&7██  &7players to join. You will be'
    - '&7█&c█&6██&0█&6██&c█&7█  &7reconnected to the hub in 5 seconds.'
    - '&7█&c█&6█████&c█&7█'
    - '&c█&6███&0█&6███&c█'
    - '&c█████████'
    - ''
  warningOldPlayers:
    - "{prefix} &7This server doesn't allow new players to join, but you can join because you are an old player."
  title:
    title: '&6&lWARNING'
    subtitle: "&7This server dont allow new players to join."